git:
  depth: 1

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - development

install:
  - haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
  - (cd ~/haxe/lib/hxcpp/git/tools/hxcpp; haxe compile.hxml)
  - (cd ~/haxe/lib/hxcpp/git/tools/build; haxe compile.hxml)
  - (cd ~/haxe/lib/hxcpp/git/tools/run; haxe compile.hxml)
  - (cd ~/haxe/lib/hxcpp/git/project; neko build.n static-linux-m64)
  - haxelib install hxjava
  - haxelib install hxlode
  - haxelib install hxSerial
  - haxelib install nodejs
  - haxelib install checkstyle
  - haxelib list

script:
  - haxelib run checkstyle -c checkstyleConfig.json -s src
  - mkdir -p outNodeJS
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then haxe build.hxml; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then haxe buildMac.hxml; fi
